import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, dataOrThrow } from "../api/client";
import { EmptyState, ErrorState, LoadingState } from "../components/AsyncState";
import { PageHeader } from "../components/Shell";

type Tab = "Dashboard" | "Discover" | "Extract" | "Review & Compare" | "Publish" | "Cloud Browser";
type UnknownRecord = Record<string, unknown>;
const tabs: Tab[] = ["Dashboard", "Discover", "Extract", "Review & Compare", "Publish", "Cloud Browser"];
const record = (value: unknown): UnknownRecord => value && typeof value === "object" ? value as UnknownRecord : {};
const text = (value: unknown): string => typeof value === "string" ? value : "";

export function AdminPage() {
  const queryClient = useQueryClient();
  const [tab, setTab] = useState<Tab>("Dashboard");
  const [goal, setGoal] = useState("");
  const [targetCount, setTargetCount] = useState(50);
  const [providerProfile, setProviderProfile] = useState("siliconflow");
  const [model, setModel] = useState("deepseek-ai/DeepSeek-V4-Flash");
  const [concurrency, setConcurrency] = useState(4);
  const [campaignId, setCampaignId] = useState("");
  const [selectedWorks, setSelectedWorks] = useState<string[]>([]);
  const [browserQuery, setBrowserQuery] = useState("");
  const [browserEntity, setBrowserEntity] = useState<"paper" | "principle" | "all">("all");
  const [yearFrom, setYearFrom] = useState("");
  const [yearTo, setYearTo] = useState("");
  const [venue, setVenue] = useState("");
  const [author, setAuthor] = useState("");
  const [institution, setInstitution] = useState("");
  const [publicationStatus, setPublicationStatus] = useState("");
  const [fullText, setFullText] = useState("");
  const [pageMin, setPageMin] = useState("");
  const [pageMax, setPageMax] = useState("");
  const [pdfMbMin, setPdfMbMin] = useState("");
  const [pdfMbMax, setPdfMbMax] = useState("");
  const [source, setSource] = useState("");
  const [cloudPresence, setCloudPresence] = useState("");
  const [syncId, setSyncId] = useState("");

  const dashboard = useQuery({ queryKey: ["admin-dashboard"], queryFn: async () => record(dataOrThrow(await api.GET("/api/v1/admin/dashboard", {}))), refetchInterval: 60_000 });
  const campaigns = useQuery({ queryKey: ["admin-campaigns"], queryFn: async () => record(dataOrThrow(await api.GET("/api/v1/admin/campaigns", {}))), refetchInterval: 5_000 });
  const campaignRows = (Array.isArray(campaigns.data?.items) ? campaigns.data.items : []) as UnknownRecord[];
  const campaign = campaignRows.find((item) => text(item.campaign_id) === campaignId);
  const papers = useQuery({
    queryKey: ["admin-papers", campaignId, yearFrom, yearTo, venue, author, institution, publicationStatus, fullText, pageMin, pageMax, pdfMbMin, pdfMbMax, source, cloudPresence],
    enabled: Boolean(campaignId),
    queryFn: async () => record(dataOrThrow(await api.GET("/api/v1/admin/campaigns/{campaign_id}/papers", { params: { path: { campaign_id: campaignId }, query: { limit: 200, offset: 0, selected: null, year_from: yearFrom ? Number(yearFrom) : null, year_to: yearTo ? Number(yearTo) : null, venue, author, institution, publication_status: publicationStatus, full_text_status: fullText, page_min: pageMin ? Number(pageMin) : null, page_max: pageMax ? Number(pageMax) : null, pdf_bytes_min: pdfMbMin ? Number(pdfMbMin) * 1024 * 1024 : null, pdf_bytes_max: pdfMbMax ? Number(pdfMbMax) * 1024 * 1024 : null, source, cloud_presence: cloudPresence } } }))),
    refetchInterval: text(campaign?.state).startsWith("discover") ? 2_000 : false,
  });
  const staging = useQuery({ queryKey: ["admin-staging", campaignId], enabled: Boolean(campaignId), queryFn: async () => record(dataOrThrow(await api.GET("/api/v1/admin/campaigns/{campaign_id}/staging", { params: { path: { campaign_id: campaignId } } }))), refetchInterval: text(campaign?.state) === "extracting" ? 2_000 : false });
  const browser = useQuery({ queryKey: ["admin-cloud-browser", browserQuery, browserEntity], enabled: tab === "Cloud Browser", queryFn: async () => record(dataOrThrow(await api.POST("/api/v1/cloud/search", { body: { entity: browserEntity, query: browserQuery, year_from: null, year_to: null, venues: [], institutions: [], areas: [], full_text_status: "", page_min: null, page_max: null, pdf_bytes_min: null, pdf_bytes_max: null, cursor: "", limit: 100, paper_cohort: 100 } }))) });
  const sync = useQuery({ queryKey: ["admin-sync", syncId], enabled: Boolean(syncId), queryFn: async () => record(dataOrThrow(await api.GET("/api/v1/admin/syncs/{sync_id}", { params: { path: { sync_id: syncId } } }))), refetchInterval: (query) => ["published", "failed", "cancelled", "needs_resolution"].includes(text(record(query.state.data).state)) ? false : 5_000 });

  const createCampaign = useMutation({
    mutationFn: async () => dataOrThrow(await api.POST("/api/v1/admin/campaigns", { body: { research_goal: goal, target_count: targetCount, provider_profile_id: providerProfile, model, concurrency } })),
    onSuccess: (value) => { setCampaignId(text(value.campaign_id)); setTab("Discover"); queryClient.invalidateQueries({ queryKey: ["admin-campaigns"] }); },
  });
  const saveSelection = useMutation({ mutationFn: async () => dataOrThrow(await api.PATCH("/api/v1/admin/campaigns/{campaign_id}/selection", { params: { path: { campaign_id: campaignId } }, body: { work_ids: selectedWorks } })), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["admin-papers"] }) });
  const extract = useMutation({ mutationFn: async () => { await saveSelection.mutateAsync(); return dataOrThrow(await api.POST("/api/v1/admin/campaigns/{campaign_id}/extract", { params: { path: { campaign_id: campaignId } }, body: { retry: false, egress_confirmed: true } })); }, onSuccess: () => { setTab("Extract"); queryClient.invalidateQueries({ queryKey: ["admin-campaigns"] }); } });
  const pauseExtraction = useMutation({ mutationFn: async (jobId: string) => dataOrThrow(await api.POST("/api/v1/admin/extractions/{job_id}/pause", { params: { path: { job_id: jobId } } })), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["admin-campaigns"] }) });
  const resumeExtraction = useMutation({ mutationFn: async (jobId: string) => dataOrThrow(await api.POST("/api/v1/admin/extractions/{job_id}/resume", { params: { path: { job_id: jobId } } })), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["admin-campaigns"] }) });
  const cancelExtraction = useMutation({ mutationFn: async (jobId: string) => dataOrThrow(await api.POST("/api/v1/admin/extractions/{job_id}/cancel", { params: { path: { job_id: jobId } } })), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["admin-campaigns"] }) });
  const decision = useMutation({ mutationFn: async ({ stageId, action, confirmed }: { stageId: string; action: "add" | "update" | "retire" | "skip"; confirmed: boolean }) => dataOrThrow(await api.PATCH("/api/v1/admin/staging/{stage_id}/decision", { params: { path: { stage_id: stageId } }, body: { decision: action, confirmed_ambiguous: confirmed } })), onSuccess: () => staging.refetch() });
  const bulkAdd = useMutation({ mutationFn: async () => dataOrThrow(await api.PATCH("/api/v1/admin/staging/decisions/bulk", { body: { stage_ids: (Array.isArray(staging.data?.items) ? staging.data.items : []).map((item) => text(record(item).stage_id)), decision: "add" } })), onSuccess: () => staging.refetch() });
  const createSync = useMutation({ mutationFn: async () => dataOrThrow(await api.POST("/api/v1/admin/campaigns/{campaign_id}/syncs", { params: { path: { campaign_id: campaignId } }, body: { confirmation: `SUBMIT ${campaignId}`, mode: "dry_run" } })), onSuccess: (value) => setSyncId(text(value.sync_id)) });
  const submitSync = useMutation({ mutationFn: async () => { const required = `PUBLISH ${syncId}`; const confirmation = window.prompt(`Type ${required} to create the checked pull request.`); if (confirmation !== required) throw new Error("Publication confirmation did not match."); return dataOrThrow(await api.POST("/api/v1/admin/syncs/{sync_id}/submit", { params: { path: { sync_id: syncId } }, body: { confirmation, mode: "github_pr" } })); }, onSuccess: () => sync.refetch() });

  useEffect(() => { if (!campaignId && campaignRows.length) setCampaignId(text(campaignRows[0].campaign_id)); }, [campaignId, campaignRows]);
  const paperRows = (Array.isArray(papers.data?.items) ? papers.data.items : []) as UnknownRecord[];
  const stagedRows = (Array.isArray(staging.data?.items) ? staging.data.items : []) as UnknownRecord[];
  const dashboardCloud = record(dashboard.data?.cloud);
  const error = dashboard.error ?? campaigns.error ?? papers.error ?? staging.error ?? sync.error ?? createCampaign.error ?? saveSelection.error ?? extract.error ?? pauseExtraction.error ?? resumeExtraction.error ?? cancelExtraction.error ?? decision.error ?? bulkAdd.error ?? createSync.error ?? submitSync.error;

  return <div className="page admin-page">
    <PageHeader eyebrow="Global Cloud governance" title="Admin Console" description="Discover public papers, run four-wide full-text extraction, compare immutable revisions, and publish checked Global Cloud changes." actions={<span className="pill success">Admin runtime</span>} />
    <nav className="admin-tabs" aria-label="Admin workflow">{tabs.map((value) => <button className={tab === value ? "selected" : ""} key={value} onClick={() => setTab(value)}>{value}</button>)}</nav>
    {error ? <ErrorState error={error} /> : null}

    {tab === "Dashboard" ? <section className="admin-dashboard">
      <div className="library-totals">{[[dashboardCloud.work_count, "Cloud papers"], [dashboardCloud.principle_count, "current Principles"], [dashboardCloud.principle_revision_count, "Principle revisions"], [dashboardCloud.principle_work_count, "provenance links"], [dashboardCloud.relation_count, "relations"], [dashboard.data?.pending_syncs, "pending syncs"]].map(([value, label]) => <div key={String(label)}><strong>{String(value ?? 0)}</strong><span>{String(label)}</span></div>)}</div>
      <article className="cloud-status-card"><span className="eyebrow">Published snapshot</span><h2>{String(dashboardCloud.release_id || "No verified release")}</h2><dl><div><dt>Commit</dt><dd><code>{String(dashboardCloud.commit_sha || "—")}</code></dd></div><div><dt>Digest</dt><dd><code>{String(dashboardCloud.content_digest || "—")}</code></dd></div><div><dt>Snapshot size</dt><dd>{Math.round(Number(dashboardCloud.snapshot_bytes ?? 0) / 1024 / 1024)} MiB</dd></div><div><dt>Embedding contract</dt><dd>{String(dashboardCloud.embedding_contract ?? "—")}</dd></div></dl>{dashboardCloud.last_error ? <div className="review-warning">Last sync: {String(dashboardCloud.last_error)}</div> : null}</article>
    </section> : null}

    {tab === "Discover" ? <section className="admin-discover">
      <form className="harvest-bar" onSubmit={(event) => { event.preventDefault(); createCampaign.mutate(); }}><label className="grow"><span>Research goal</span><input value={goal} onChange={(event) => setGoal(event.target.value)} placeholder="Enter a bounded scientific research goal" /></label><label><span>Target papers (1–20,000)</span><input type="number" min={1} max={20000} value={targetCount} onChange={(event) => setTargetCount(Number(event.target.value))} /></label><label><span>Provider profile</span><input value={providerProfile} onChange={(event) => setProviderProfile(event.target.value)} /></label><label><span>Model</span><input value={model} onChange={(event) => setModel(event.target.value)} /></label><label><span>Workers (4–8)</span><input type="number" min={4} max={8} value={concurrency} onChange={(event) => setConcurrency(Number(event.target.value))} /></label><button className="primary" disabled={goal.trim().length < 8 || createCampaign.isPending}>{createCampaign.isPending ? "Discovering…" : "Discover papers"}</button></form>
      <div className="admin-campaign-picker"><label><span>Campaign</span><select value={campaignId} onChange={(event) => { setCampaignId(event.target.value); setSelectedWorks([]); }}>{campaignRows.map((item) => <option key={text(item.campaign_id)} value={text(item.campaign_id)}>{text(item.research_goal)} · {text(item.state)}</option>)}</select></label></div>
      <div className="admin-filters"><label><span>Year from</span><input value={yearFrom} onChange={(event) => setYearFrom(event.target.value)} /></label><label><span>Year to</span><input value={yearTo} onChange={(event) => setYearTo(event.target.value)} /></label><label><span>Venue</span><input value={venue} onChange={(event) => setVenue(event.target.value)} /></label><label><span>Author</span><input value={author} onChange={(event) => setAuthor(event.target.value)} /></label><label><span>Institution</span><input value={institution} onChange={(event) => setInstitution(event.target.value)} /></label><label><span>Publication status</span><input value={publicationStatus} onChange={(event) => setPublicationStatus(event.target.value)} placeholder="published, preprint…" /></label><label><span>Full text</span><select value={fullText} onChange={(event) => setFullText(event.target.value)}><option value="">Any</option><option>available</option><option>unavailable</option><option>unknown</option><option>probe_failed</option></select></label><label><span>Pages min</span><input type="number" min={1} value={pageMin} onChange={(event) => setPageMin(event.target.value)} /></label><label><span>Pages max</span><input type="number" min={1} value={pageMax} onChange={(event) => setPageMax(event.target.value)} /></label><label><span>PDF MiB min</span><input type="number" min={0} value={pdfMbMin} onChange={(event) => setPdfMbMin(event.target.value)} /></label><label><span>PDF MiB max</span><input type="number" min={0} value={pdfMbMax} onChange={(event) => setPdfMbMax(event.target.value)} /></label><label><span>Source</span><input value={source} onChange={(event) => setSource(event.target.value)} /></label><label><span>Cloud presence</span><select value={cloudPresence} onChange={(event) => setCloudPresence(event.target.value)}><option value="">Any</option><option value="new">New</option><option value="exact">Exact</option><option value="strong_id">Existing ID</option><option value="ambiguous">Ambiguous</option></select></label></div>
      {papers.isLoading ? <LoadingState label="Retrieving and enriching public papers…" /> : null}
      {!papers.isLoading && !paperRows.length ? <EmptyState title="No campaign papers yet"><p>Start a discovery campaign; partial provider outages remain visible as degraded results.</p></EmptyState> : <div className="admin-paper-table">{paperRows.map((paper) => { const id = text(paper.work_id); return <article key={id}><label className="inline-check"><input type="checkbox" checked={selectedWorks.includes(id)} onChange={(event) => setSelectedWorks((current) => event.target.checked ? [...current, id] : current.filter((value) => value !== id))} /><span /></label><div><strong>{text(paper.title)}</strong><small>{text(paper.venue)} · {String(paper.year ?? "unknown year")} · {String(paper.availability_status)} · Cloud: {String(paper.cloud_presence)}</small><p>{text(paper.abstract).slice(0, 280)}</p></div></article>; })}</div>}
      <div className="goal-run-actions"><span>{selectedWorks.length} selected · new runs require at least four</span><button className="primary" disabled={selectedWorks.length < 4 || extract.isPending} onClick={() => extract.mutate()}>Extract selected papers</button></div>
    </section> : null}

    {tab === "Extract" ? <section><div className="cloud-status-card"><span className="eyebrow">Durable extraction</span><h2>{text(record(campaign?.extraction).state) || text(campaign?.state) || "No active campaign"}</h2><p>Four paper workers are dispatched whenever four or more units remain. Pause stops new dispatch; active requests finish cleanup. PDFs and normalized source text are always deleted before a unit can succeed.</p><dl><div><dt>Job</dt><dd><code>{text(record(campaign?.extraction).job_id) || "—"}</code></dd></div><div><dt>Campaign</dt><dd>{text(campaign?.research_goal) || "—"}</dd></div><div><dt>Progress</dt><dd>{Math.round(Number(record(campaign?.extraction).progress ?? 0) * 100)}% · {String(record(campaign?.extraction).status_message || "waiting")}</dd></div></dl><div className="goal-run-actions">{(() => { const extraction = record(campaign?.extraction); const jobId = text(extraction.job_id); const state = text(extraction.state); return <><button disabled={!jobId || !["queued", "running", "resuming"].includes(state)} onClick={() => pauseExtraction.mutate(jobId)}>Pause after active cleanup</button><button disabled={!jobId || !["paused", "interrupted", "pausing"].includes(state)} onClick={() => resumeExtraction.mutate(jobId)}>Resume</button><button disabled={!jobId || ["succeeded", "cancelled", "failed"].includes(state)} onClick={() => { if (window.confirm("Cancel queued papers? Active workers will finish mandatory cleanup.")) cancelExtraction.mutate(jobId); }}>Cancel</button></>; })()}</div></div><div className="admin-paper-table">{paperRows.filter((paper) => Boolean(paper.selected)).map((paper) => <article key={text(paper.work_id)}><span className={`pill ${paper.state === "staged" ? "success" : ""}`}>{String(paper.state)}</span><div><strong>{text(paper.title)}</strong><small>{String(paper.availability_status)} · temporary source deletion is mandatory</small></div></article>)}</div></section> : null}

    {tab === "Review & Compare" ? <section><div className="goal-run-actions"><span>{stagedRows.length} staged records · ambiguous matches are excluded from bulk action</span><button onClick={() => bulkAdd.mutate()} disabled={!stagedRows.length}>Select all eligible as add</button></div>{!stagedRows.length ? <EmptyState title="Nothing staged"><p>Complete extraction before comparing proposed and current Cloud records.</p></EmptyState> : <div className="staging-grid">{stagedRows.map((item) => { const current = record(item.current); const proposed = record(item.proposed); const ambiguous = item.match_kind === "ambiguous"; return <article key={text(item.stage_id)}><header><span className="pill">{String(item.entity)}</span><span className={`pill ${item.match_kind === "new" ? "success" : ""}`}>{String(item.match_kind)}</span></header><div className="side-by-side"><div><small>Current Cloud</small><strong>{text(current.title) || text(current.work_id) || "No matching record"}</strong><p>{text(current.claim)}</p></div><div><small>Proposed</small><strong>{text(proposed.title) || text(proposed.work_id)}</strong><p>{text(proposed.claim)}</p></div></div><p className="muted">Match reason: {String(item.match_reason)} · similarity {Number(item.similarity ?? 0).toFixed(2)}</p><div className="decision-actions">{(["add", "update", "retire", "skip"] as const).map((action) => <button className={item.decision === action ? "primary" : ""} key={action} onClick={() => decision.mutate({ stageId: text(item.stage_id), action, confirmed: ambiguous })}>{action}</button>)}</div></article>; })}</div>}</section> : null}

    {tab === "Publish" ? <section className="cloud-status-card"><span className="eyebrow">Checked PR + auto-merge</span><h2>Submit reviewed changeset</h2><p>Every item must have a decision. Updates append revision N+1. CI validates schemas, review attestation, public links and forbidden data, then rebuilds release snapshots and advances latest.json only after independent verification.</p><div className="goal-run-actions"><button className="primary" onClick={() => { if (window.confirm("Submit the reviewed changeset for validation? Local staging is retained until publication succeeds.")) createSync.mutate(); }} disabled={!campaignId || !stagedRows.length || stagedRows.some((item) => !item.decision) || createSync.isPending}>Create reviewed draft</button><button onClick={() => submitSync.mutate()} disabled={!syncId || text(sync.data?.state) !== "reviewed" || submitSync.isPending}>Create checked GitHub PR</button></div>{syncId ? <div className="review-warning"><strong>{text(sync.data?.state) || "Loading publication state…"}</strong><br />Sync {syncId}{text(sync.data?.pr_url) ? <> · <a href={text(sync.data?.pr_url)} target="_blank" rel="noreferrer">Open PR</a></> : null}{text(sync.data?.release_id) ? <> · Release {text(sync.data?.release_id)}</> : null}. Local staging remains available until the verified state is published.</div> : null}</section> : null}

    {tab === "Cloud Browser" ? <section><div className="harvest-bar"><label className="grow"><span>Semantic Cloud search</span><input value={browserQuery} onChange={(event) => setBrowserQuery(event.target.value)} placeholder="Search any paper or Principle" /></label><label><span>Entity</span><select value={browserEntity} onChange={(event) => setBrowserEntity(event.target.value as typeof browserEntity)}><option value="all">All</option><option value="paper">Papers</option><option value="principle">Principles</option></select></label></div>{browser.isLoading ? <LoadingState label="Searching the pinned Cloud snapshot…" /> : <div className="admin-paper-table">{(Array.isArray(browser.data?.items) ? browser.data.items : []).map((item) => <article key={text(record(item).id)}><span className="pill">{String(record(item).entity)}</span><div><strong>{text(record(item).title)}</strong><small>{text(record(item).venue) || text(record(item).area)} · {text(record(item).match_path)}</small><p>{text(record(item).claim) || text(record(item).abstract).slice(0, 260)}</p></div></article>)}</div>}</section> : null}
  </div>;
}
